### ISSUE TITLE
Support new 'adaptive' icons in Android 8+

### ISSUE THREAD

**Issue by fiznool** [dwmkerr/app-icon#60]
Android 8+ has a set of new guidelines for app icons: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

The general idea is that you provide an icon and a background colour. The icon has transparency, and is overlaid onto the background colour. The whole thing is then masked by the device, to produce a circle, square, rounded square, etc. To facilitate a circular mask, you can also specify a different icon to use for circular masks.

I'm adding this issue more as a 'nice to have', as it would require a few changes for sure! Some way of asking:

- whether this behaviour is desired at all (using the 'legacy' launcher icons will still work)
- if so, whether a different icon file should be used, and what background colour to use

and then the associated changes to the XML files as described in the above link.

Unfortunately I don't have any spare time to dedicate to a PR right now, but thought I'd bring it up in case it was on your roadmap.

Thanks for a great library - it's been a big timesaver for me 😄

**Comment by dwmkerr** [comment]
I think it would be great to support this, thanks for sharing! I'll take a look at it when I get a little time, probably a couple of weeks from now :)

**Comment by valposv** [comment]
@dwmkerr what's the status of this issue? Is it expected to be done soon?

**Comment by dwmkerr** [comment]
Hi @the-rs it'll be a couple of weeks still before I can look at this, but will be using it for a project I'm working on then so will definitely be getting onto it1

**Comment by hrhosni** [comment]
Hey @dwmkerr . Just looking for an update on this issue?
Thanks!

**Comment by dwmkerr** [comment]
I got the Windows build and tests working which slowed me down, I can actually and finally look at this now.

One thing I'd love is a suggestion on how we manage the multiple images - should it be something like a convention to have:

```
icon.png
icon.adaptive.layer1.png
icon.adaptive.layer2.png
icon.adaptive.mask.png
```

Or command line flags? At the moment, here are my design goals:

1. For people _not_ using the feature, it should not interfere with them
2. For people who _do_ want to use the feature, they should be able to use it with very little effort and intuitive documentation (I'm even thinking of something like `app-icon init` to create template icons).
3. People should be able to keep the icons _outside_ of the root of their project if they want, to avoid cluttering the base

Does anyone else have any suggestions?

**Comment by hrhosni** [comment]
Hi @dwmkerr !
Well if we can mimic whatever the tool that's built in Android Studio does, it'd be great. I'm not sure where it places the adaptive icons and what it names them but everything works great when I use it.

As for the design goals, they seem pretty comprehensive to me.

Again, thanks a lot for your efforts. They're much appreciated.

**Comment by valposv** [comment]
Hello @dwmkerr ! 
I think command line flags would be more suitable rather than explicit creation. Template icons is also pretty useful feature to have. Can we expect adaptive icons support soon?
Regards. Thanks

**Comment by dwmkerr** [comment]
Yep will be pushing it in shortly!

**Comment by valposv** [comment]
@dwmkerr hello, what's the status?

**Comment by pie6k** [comment]
@dwmkerr any update on this?

**Comment by dwmkerr** [comment]
OK for those watching the issue, here's the progress. I'll keep the updates on this comment:

- [x] Add the `init` command, which will generate the initial icon (#77).
- [x] Update the docs to indicate we are bringing in experimental support for adaptive icons, via the forthcoming `--adaptive-icons` flag #80
- [x] Introduce the `--adaptive-icons` parameter to the `init` command, which will create adaptive icons #81
- [x] Introduce the `--adaptive-icons` parameter to the `generate` command which will generate them #86
- [x] show the icons in the README to make it clear what will be generated

## Current Issues
- [x] Captions are not supported for Adaptive Icons #90
- [x] The Adaptive Icons are not visually in the same style as the 'standard' icons #90

**Comment by dwmkerr** [comment]
OK! Finally 😄 

This took a _lot_ longer than expected to get right, and I am still not 100% sure it is perfect, but adaptive icon support is available in [v0.11.0](https://github.com/dwmkerr/app-icon/releases/tag/v0.11.0)

In short, first create some template icons:

```sh
$ app-icon init --adaptive-icons
icon.png created
icon.background.png created
icon.foreground.png created
```

This will create the icons you can use as your main template icons. Then spit out each size with:

```sh
$ app-icon generate --adaptive-icons
```

At the moment, all adaptive icon features are 'opt-in' with the `--adaptive-icons` flag, until I've seen that it seems to be working well for a large enough group of people.
