### ISSUE TITLE
feature: prune

### ISSUE THREAD

**Issue by dwmkerr** [dwmkerr/app-icon#85]
**Problem**

If there are icons which have _not_ been generated (such as the round icons in issue #71), then even after running `generate` the expected icon might not be shown on certain devices.

**Solution**

Warn user when extraneous icons are present, and offer an option to have them removed, meaning only the icons created by app-icon will be in the project.

**Specs**

The 'prune' feature would have two parts:

**Identify Extraneous Icons**

When running `generate`, if _extra_ icons are detected (i.e. icons which have not been generated), then a warning should be shown, such as:

```
$ app-icon generate.
...
Warning: Some icons in the project have not been replaced with this icon. Your icon might not be shown on all devices. Run generate with the --prune flat to remove these icons.
```

**Prune Extra Icons**

If the `--prune` flag is specified, any extraneous icons should be deleted.

**Tasks**

- [ ] Lock down technical specs
- [ ] Implement warning on generate
- [ ] Implement `--prune` flag on generate
